### ISSUE TITLE
Implement AQ&U correction 

### ISSUE THREAD

**Issue by birdowl** [codeminders/violet-air#13]
https://thebolditalic.com/amp/p/562923a55226

Edit: 9/1/2020: PurpleAir will soon feature a 3rd correction factor specifically created by the EPA. In the meantime, EPA recommends that you use AQandU instead of LRAPA, especially if the AQI is higher than 150. From the EPA: “The US EPA correction will be available on PurpleAir.com as a selection shortly. Until then, the AQ&U correction more closely matches our correction throughout a wide range of concentrations while LRAPA shows significant underestimation above 65 ug/m3 [150 AQI].” (bracketed AQI added by me) If you’re curious about the EPA formula, see note #5 at the end of this article. Note that an earlier version of this article you’re reading suggested using LRAPA. This was before the EPA gave me this updated recommendation. For more on LRAPA vs. AQandU, see note 6 at the end of this article.

**Comment by vzaliva** [comment]
Why not just implement EPA formula which is more accurate than AQ&U?

**Comment by vzaliva** [comment]
Link to PDF with EPA formula: https://cfpub.epa.gov/si/si_public_file_download.cfm?p_download_id=540979&Lab=CEMM

**Comment by birdowl** [comment]
done
